import models.assessment_method
import models.cilo
import models.cilo_assessment_method
import models.cilo_dependency
import models.course_designer
import models.course_type
import models.course
import models.lecturer
import models.program_degree
import models.semester
import models.student
import models.user
import models.saveable_model
import models.program